name: CI

on:
    pull_request:
        branches:
        - '*'
    push:
        branches:
        - master
        - main
    workflow_dispatch:

jobs:
    specs:
        name: specs
        strategy:
            matrix:
                runner:
                    - actuated-arm64
                    -  actuated
        runs-on: ${{ matrix.runner }}
        steps:
        - uses: actions/checkout@v3
        - name: Check specs
          run: |
            ./specs.sh

    registry-mirror:
        strategy:
            matrix:
                runner:
                    - actuated-arm64
                    -  actuated
        runs-on: ${{ matrix.runner }}

        steps:

        - name: Setup mirror
          uses: self-actuated/hub-mirror@master

        - name: Checkout
          uses: actions/checkout@v3

        - name: Pull image using cache
          run: |
            docker pull alpine:latest
          shell: bash

    kind-test:
      name: Test KIND 1.7.0
      runs-on: ${{ matrix.runner }}
      strategy:
        fail-fast: false
        matrix:
          k8s-release:
            - 'v1.27.3'
            - 'v1.26.6'
            - 'v1.25.11'
            - 'v1.24.15'
            - 'v1.23.17'
          runner:
            - actuated
            - ubuntu-latest
      steps:
          # Prevent any image throttling from DockerHub (e.g. for Kind)
          - name: Set up Actuated mirror
            uses: self-actuated/hub-mirror@master

          - name: Create k8s Kind Cluster
            uses: helm/kind-action@v1.8.0
            timeout-minutes: 5
            with:
              node_image: kindest/node:${{ matrix.k8s-release }}
              cluster_name: kind
              wait: 300s

    kind-test-18:
      name: Test KIND 1.8.0
      runs-on: ${{ matrix.runner }}
      strategy:
        fail-fast: false
        matrix:
          k8s-release:
            - 'v1.27.3'
            - 'v1.26.6'
            - 'v1.25.11'
            - 'v1.24.15'
            - 'v1.23.17'
          runner:
            - actuated
            - ubuntu-latest
      steps:
        # Prevent any image throttling from DockerHub (e.g. for Kind)
        - name: Set up Actuated mirror
          uses: self-actuated/hub-mirror@master

        - name: Create k8s Kind Cluster
          uses: helm/kind-action@v1.8.0
          timeout-minutes: 5
          with:
            node_image: kindest/node:${{ matrix.k8s-release }}
            cluster_name: kind
            wait: 300s
