name: CI

on:
    pull_request:
        branches:
        - '*'
    push:
        branches:
        - master
        - main
    workflow_dispatch:

jobs:
    specs:
        name: specs
        strategy:
            matrix:
                runner:
                    - actuated-arm64
                    -  actuated
        runs-on: ${{ matrix.runner }}
        steps:
        - uses: actions/checkout@v3
        - name: Check specs
          run: |
            ./specs.sh

    registry-mirror:
        strategy:
            matrix:
                runner:
                    - actuated-arm64
                    -  actuated
        runs-on: ${{ matrix.runner }}

        steps:

        - name: Setup mirror
          uses: self-actuated/hub-mirror@master

        - name: Checkout
          uses: actions/checkout@v3

        - name: Pull image using cache
          run: |
            docker pull alpine:latest
          shell: bash

    ci-integration-test:
      name: Run integration tests
      runs-on: actuated-4cpu-16gb
      strategy:
        fail-fast: false
        matrix:
          k8s-release:
            - 'v1.25.0'
            - 'v1.24.4'
            - 'v1.23.5'
          kind-action-version:
            - 'v1.7.0'
            - 'v1.8.0'
      steps:
          # Prevent any image throttling from DockerHub (e.g. for Kind)
          - name: Set up Actuated mirror
            uses: self-actuated/hub-mirror@master

          - name: Create k8s Kind Cluster
            uses: helm/kind-action@${{ matrix.kind-action-version }}
            timeout-minutes: 5
            with:
              node_image: kindest/node:${{ matrix.k8s-release }}
              cluster_name: kind
