name: CI

on:
    pull_request:
        branches:
        - '*'
    push:
        branches:
        - master
        - main
    workflow_dispatch:

jobs:
    specs:
        name: specs
        strategy:
            matrix:
                runner:
                    - actuated-arm64
                    -  actuated
        runs-on: ${{ matrix.runner }}
        steps:
        - uses: actions/checkout@v3
        - name: Check specs
          run: |
            ./specs.sh

    registry-mirror:
        strategy:
            matrix:
                runner:
                    - actuated-arm64
                    -  actuated
        runs-on: ${{ matrix.runner }}

        steps:

        - name: Setup mirror
          uses: self-actuated/hub-mirror@master

        - name: Checkout
          uses: actions/checkout@v3

        - name: Pull image using cache
          run: |
            docker pull alpine:latest
          shell: bash
