name: Openshift local
on:
    workflow_dispatch:

jobs:
    # https://console.redhat.com/openshift/create/local
    create-openshift-local-runner:
        runs-on: actuated-8cpu-16gb
        steps:
            - name: Install packages
              run: sudo apt-get update && sudo apt-get install -y qemu-kvm libvirt-daemon libvirt-daemon-system network-manager
              shell: bash

            - name: Set up user
              run: |
                sudo groupadd libvirt || true
                sudo usermod -a -G libvirt $USER
              shell: bash

            - name: Download CRC
              run: curl -sSfLO https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
              shell: bash

            - name: Extract CRC
              run: tar -xvf crc-linux-amd64.tar.xz
              shell: bash

            - name: Move to path
              run: sudo cp -vf crc-linux-*-amd64/crc /usr/local/bin/ && sudo chmod a+x /usr/local/bin/crc
              shell: bash

            - name: Provide pull secret
              run: echo '${{ secrets.OPENSHIFT_PULL_SECRET }}' > ./pull-secret.txt
              shell: bash

            - name: Configure CRC
              run: |
                /usr/local/bin/crc config set pull-secret-file "$PWD/pull-secret.txt"
                /usr/local/bin/crc config set kubeadmin-password admin
                /usr/local/bin/crc config set consent-telemetry no
                /usr/local/bin/crc config set disable-update-check true
                /usr/local/bin/crc config set skip-check-user-in-libvirt-group true
              shell: bash

            # - name: Set up CRC
            #   run: /usr/local/bin/crc setup
            #   shell: bash

            # - name: Start up CRC VM
            #   run: /usr/local/bin/crc start
            #   shell: bash

            - name: Allow SSH login remotely to work with it
              uses: self-actuated/connect-ssh@master
